# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('article_content', models.CharField(max_length=1024)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
